const fmt = (n) => (n == null || isNaN(n) ? '—' : '₹' + Number(n).toLocaleString('en-IN'))

function productName(item) {
  return item.name || item.product?.name || item.productName || '—'
}

function unitPrice(item) {
  const p = item.unitPrice ?? item.product?.price ?? item.price
  return p != null ? Number(p) : null
}

function lineTotal(item, price, qty) {
  if (item.total != null) return Number(item.total)
  return price != null ? price * qty : null
}

export default function InvoicePrintView({ invoice, from }) {
  if (!invoice) return null

  const items = invoice.rawItems || []
  const billedTo = invoice.dealerInfo || {}

  return (
    <div className="invoice-doc">
      <div className="invoice-doc-head">
        <div className="invoice-doc-brand">
          <img src="/assets/PNG%20LOGO.png" alt="Vbike" />
          <div>
            <div className="invoice-doc-company">{from?.company || 'Vbike'}</div>
            {from?.email && <div>{from.email}</div>}
            {from?.phone && <div>{from.phone}</div>}
          </div>
        </div>
        <div className="invoice-doc-meta">
          <h2>INVOICE</h2>
          <div><span className="muted">Invoice #</span> {invoice.invoiceNumber || invoice.id}</div>
          {invoice.soNumber && invoice.soNumber !== '—' && (
            <div><span className="muted">SO Number</span> {invoice.soNumber}</div>
          )}
          <div><span className="muted">Date</span> {invoice.date}</div>
          <div><span className="muted">Payment Status</span> {invoice.status}</div>
        </div>
      </div>

      <div className="invoice-doc-parties">
        <div>
          <div className="muted" style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.5 }}>Billed To</div>
          <div style={{ fontWeight: 700, marginTop: 4 }}>{billedTo.companyName || invoice.dealer || '—'}</div>
          {billedTo.ownerName && <div>{billedTo.ownerName}</div>}
          {billedTo.phone && <div>{billedTo.phone}</div>}
          {billedTo.email && <div>{billedTo.email}</div>}
        </div>
      </div>

      <table className="invoice-doc-table">
        <thead>
          <tr>
            <th style={{ width: 36 }}>#</th>
            <th>Product</th>
            <th>Type</th>
            <th>Qty</th>
            <th>Unit Price</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {items.length === 0 ? (
            <tr><td colSpan={6} style={{ textAlign: 'center' }}>No items</td></tr>
          ) : (
            items.map((item, idx) => {
              const price = unitPrice(item)
              const qty = Number(item.quantity) || 0
              const total = lineTotal(item, price, qty)
              return (
                <tr key={item._id || idx}>
                  <td>{idx + 1}</td>
                  <td>{productName(item)}</td>
                  <td>{item.productType || '—'}</td>
                  <td>{qty}</td>
                  <td>{price != null ? fmt(price) : '—'}</td>
                  <td>{total != null ? fmt(total) : '—'}</td>
                </tr>
              )
            })
          )}
        </tbody>
      </table>

      <div className="invoice-doc-totals">
        <div><span>Subtotal</span><span>{fmt(invoice.subTotal)}</span></div>
        <div><span>Tax</span><span>{fmt(invoice.tax)}</span></div>
        {!!invoice.discount && <div><span>Discount</span><span>-{fmt(invoice.discount)}</span></div>}
        <div className="invoice-doc-grand"><span>Grand Total</span><span>{fmt(invoice.grandTotal)}</span></div>
        {invoice.amountPaid != null && <div><span>Amount Paid</span><span>{fmt(invoice.amountPaid)}</span></div>}
        {invoice.balanceDue != null && <div className="invoice-doc-balance"><span>Balance Due</span><span>{fmt(invoice.balanceDue)}</span></div>}
      </div>

      {invoice.remarks && (
        <div className="invoice-doc-remarks"><b>Remarks:</b> {invoice.remarks}</div>
      )}

      <div className="invoice-doc-footer">Thank you for your business — generated by Vbike DMS</div>
    </div>
  )
}
